// Auto-generated from Carpeta Modelo — real pixel dimensions
const IMG_DIMS = {
  // _comun
  "{code}_comun/{code}_com_docente.png":       {w:436,  h:261,  ext:"png"},
  "{code}_comun/{code}_comunicado.jpg":         {w:1000, h:1000, ext:"jpg"},
  "{code}_comun/{code}_logo_footer.png":        {w:549,  h:155,  ext:"png"},
  "{code}_comun/{code}_logo_mediano.png":       {w:549,  h:155,  ext:"png"},
  "{code}_comun/{code}_semana.png":             {w:1006, h:76,   ext:"png"},
  "{code}_comun/afianzamiento/{code}_banner_afi_s01.png":      {w:1283, h:250, ext:"png"},
  "{code}_comun/aplicacion/{code}_banner_aplic_s01.png":       {w:1283, h:250, ext:"png"},
  "{code}_comun/contenido/{code}_banner_cont_s01.png":         {w:1283, h:250, ext:"png"},
  "{code}_comun/contenido/{code}_banner_mat_com_s01.png":      {w:932,  h:137, ext:"png"},
  "{code}_comun/contenido/{code}_banner_mat_ob_s01.png":       {w:932,  h:137, ext:"png"},
  "{code}_comun/contenido/{code}_biblioteca.png":              {w:800,  h:156, ext:"png"},
  "{code}_comun/contenido/{code}_icono_audiolibros.png":       {w:770,  h:1001,ext:"png"},
  "{code}_comun/contenido/{code}_icono_grafico.png":           {w:771,  h:1001,ext:"png"},
  "{code}_comun/contenido/{code}_icono_libro.png":             {w:771,  h:1001,ext:"png"},
  "{code}_comun/contenido/{code}_icono_presentacion.png":      {w:771,  h:1001,ext:"png"},
  "{code}_comun/contenido/{code}_icono_resumenes.png":         {w:771,  h:1001,ext:"png"},
  "{code}_comun/contenido/{code}_icono_video.png":             {w:771,  h:1001,ext:"png"},
  "{code}_comun/contenido/{code}_semana.png":                  {w:1006, h:76,  ext:"png"},
  "{code}_comun/foro/{code}_banner_foro_s01.png":              {w:1283, h:250, ext:"png"},
  "{code}_comun/gamificacion/{code}_banner_gam_s01.png":       {w:1283, h:250, ext:"png"},
  "{code}_comun/plan/{code}_banner_plan_s01.png":              {w:1283, h:250, ext:"png"},
  "{code}_comun/preg_reflexiva/{code}_banner_reflex_s01.png":  {w:1283, h:250, ext:"png"},
  "{code}_comun/proyecto/{code}_banner_proyecto_s01.png":      {w:1283, h:250, ext:"png"},
  // hito1
  "{code}_hito1/{code}_banner_h1.png":         {w:1283, h:250,  ext:"png"},
  "{code}_hito1/{code}_pestana1_h1.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito1/{code}_pestana2_h1.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito1/{code}_pestana3_h1.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito1/{code}_pestana4_h1.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito1/{code}_pestana5_h1.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito1/{code}_pestana6_h1.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito1/{code}_pestana6_h1-07.png":     {w:1006, h:67,   ext:"png"},
  "{code}_hito1/{code}_ruta_h1.png":            {w:2000, h:1156, ext:"png"},
  "{code}_hito1/{code}_semana.png":             {w:1006, h:76,   ext:"png"},
  // hito2
  "{code}_hito2/{code}_banner_h2.png":         {w:1283, h:250,  ext:"png"},
  "{code}_hito2/{code}_pestana1_h2.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito2/{code}_pestana2_h2.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito2/{code}_pestana3_h2.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito2/{code}_pestana4_h2.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito2/{code}_pestana5_h2.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito2/{code}_pestana6_h2.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito2/{code}_pestana7_h2.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito2/{code}_ruta_h2.png":            {w:1120, h:1108, ext:"png"},
  "{code}_hito2/{code}_semana.png":             {w:1006, h:76,   ext:"png"},
  // hito3
  "{code}_hito3/{code}_banner_h3.png":         {w:1283, h:250,  ext:"png"},
  "{code}_hito3/{code}_pestana1_h3.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito3/{code}_pestana2_h3.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito3/{code}_pestana3_h3.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito3/{code}_pestana4_h3.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito3/{code}_pestana5_h3.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito3/{code}_pestana6_h3.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito3/{code}_pestana7_h3.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito3/{code}_ruta_h3.png":            {w:1000, h:1746, ext:"png"},
  "{code}_hito3/{code}_semana.png":             {w:1006, h:76,   ext:"png"},
  // hito4
  "{code}_hito4/{code}_banner_h4.png":         {w:1283, h:250,  ext:"png"},
  "{code}_hito4/{code}_pestana1_h4.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito4/{code}_pestana2_h4.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito4/{code}_pestana3_h4.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito4/{code}_pestana4_h4.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito4/{code}_pestana5_h4.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito4/{code}_pestana6_h4.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito4/{code}_pestana7_h4.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito4/{code}_ruta_h4.png":            {w:1000, h:1065, ext:"png"},
  "{code}_hito4/{code}_semana.png":             {w:1006, h:76,   ext:"png"},
  // hito5
  "{code}_hito5/{code}_banner_h5.png":         {w:1283, h:250,  ext:"png"},
  "{code}_hito5/{code}_pestana1_h5.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito5/{code}_pestana2_h5.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito5/{code}_pestana3_h5.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito5/{code}_pestana4_h5.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito5/{code}_pestana5_h5.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito5/{code}_pestana6_h5.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito5/{code}_pestana7_h5.png":        {w:1006, h:67,   ext:"png"},
  "{code}_hito5/{code}_ruta_h5.png":            {w:1000, h:1343, ext:"png"},
  "{code}_hito5/{code}_semana.png":             {w:1006, h:76,   ext:"png"},
  // inicio
  "{code}_inicio/{code}_aprendizaje_h1.png":   {w:376,  h:872,  ext:"png"},
  "{code}_inicio/{code}_aprendizaje_h2.png":   {w:376,  h:872,  ext:"png"},
  "{code}_inicio/{code}_aprendizaje_h3.png":   {w:376,  h:872,  ext:"png"},
  "{code}_inicio/{code}_aprendizaje_h4.png":   {w:376,  h:872,  ext:"png"},
  "{code}_inicio/{code}_aprendizaje_h5.png":   {w:376,  h:872,  ext:"png"},
  "{code}_inicio/{code}_com_docente.png":       {w:436,  h:261,  ext:"png"},
  "{code}_inicio/{code}_header.png":            {w:1005, h:686,  ext:"png"},
  "{code}_inicio/{code}_pestana1.png":          {w:1006, h:67,   ext:"png"},
  "{code}_inicio/{code}_pestana2.png":          {w:1006, h:67,   ext:"png"},
  "{code}_inicio/{code}_pestana3.png":          {w:1006, h:67,   ext:"png"},
  "{code}_inicio/{code}_pestana4.png":          {w:1006, h:67,   ext:"png"},
  "{code}_inicio/{code}_pestana5.png":          {w:1006, h:67,   ext:"png"},
  "{code}_inicio/{code}_pestana6.png":          {w:1006, h:66,   ext:"png"},
  "{code}_inicio/{code}_pestana7.png":          {w:1006, h:66,   ext:"png"},
  "{code}_inicio/{code}_ruta_inicio.png":       {w:2000, h:1414, ext:"png"},
  "{code}_inicio/{code}_tar_hito1.png":         {w:1005, h:488,  ext:"png"},
  "{code}_inicio/{code}_tar_hito2.png":         {w:1005, h:488,  ext:"png"},
  "{code}_inicio/{code}_tar_hito3.png":         {w:1005, h:488,  ext:"png"},
  "{code}_inicio/{code}_tar_hito4.png":         {w:1005, h:488,  ext:"png"},
  "{code}_inicio/{code}_tar_hito5.png":         {w:1005, h:488,  ext:"png"},
  // tarjeta
  "{code}_tarjeta/{code}_tarjeta.png":          {w:800,  h:446,  ext:"png"},
};

/**
 * Resolve a template key like "{code}_comun/{code}_semana.png"
 * using the actual lower-case code, then look up dimensions.
 */
function getDims(templateKey, codeLower) {
  const resolved = templateKey.replace(/\{code\}/g, codeLower);
  // Try resolved key first, then original template key
  return IMG_DIMS[resolved] || IMG_DIMS[templateKey] || null;
}
